import Link from "next/link";
import { ArrowRight, Brain, CalendarDays, Sparkles, Timer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const features = [
  {
    title: "AI timetable generation",
    description: "Upload your schedule and Forge extracts events into a smart weekly graph.",
    icon: Brain,
  },
  {
    title: "Focus Mode",
    description: "Distraction-free Pomodoro and deep work modes for peak execution.",
    icon: Timer,
  },
  {
    title: "Adaptive scheduling",
    description: "Missed a session? Forge rebalances your week in real time.",
    icon: CalendarDays,
  },
  {
    title: "Smart insights",
    description: "Get actionable reasoning for each study block generated by AI.",
    icon: Sparkles,
  },
];

export default function Home() {
  return (
    <main>
      <section className="mx-auto max-w-6xl px-4 pb-20 pt-10 md:px-6 md:pt-16">
        <div className="mb-8 inline-flex items-center rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-300">
          Premium AI productivity for students
        </div>
        <h1 className="max-w-3xl text-4xl font-bold tracking-tight text-white md:text-6xl">
          Your AI-powered personal study planner
        </h1>
        <p className="mt-4 max-w-2xl text-slate-300 md:text-lg">
          Forge transforms messy schedules into adaptive study plans that feel calm, motivating, and always one step ahead.
        </p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link href="/auth">
            <Button size="lg">Get Started</Button>
          </Link>
          <Link href="/app/dashboard">
            <Button variant="secondary" size="lg">
              Try Demo <ArrowRight className="ml-1 size-4" />
            </Button>
          </Link>
        </div>
      </section>

      <section className="mx-auto grid max-w-6xl gap-4 px-4 md:grid-cols-2 md:px-6">
        {features.map((feature) => {
          const Icon = feature.icon;
          return (
            <Card key={feature.title}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <Icon className="size-4 text-cyan-300" />
                  {feature.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-slate-300">{feature.description}</CardContent>
            </Card>
          );
        })}
      </section>

      <section className="mx-auto max-w-6xl px-4 py-20 md:px-6">
        <Card className="overflow-hidden border-violet-300/20 bg-gradient-to-br from-indigo-500/20 to-cyan-500/10">
          <CardContent className="grid gap-4 p-6 md:grid-cols-3">
            <div className="rounded-xl bg-[#101a3a] p-4">
              <p className="text-sm text-slate-400">Today&apos;s sessions</p>
              <p className="text-2xl font-semibold text-white">4</p>
            </div>
            <div className="rounded-xl bg-[#101a3a] p-4">
              <p className="text-sm text-slate-400">Study streak</p>
              <p className="text-2xl font-semibold text-emerald-300">12 days</p>
            </div>
            <div className="rounded-xl bg-[#101a3a] p-4">
              <p className="text-sm text-slate-400">AI confidence</p>
              <p className="text-2xl font-semibold text-cyan-300">94%</p>
            </div>
          </CardContent>
        </Card>
      </section>

      <footer className="border-t border-white/10 px-4 py-8 text-center text-sm text-slate-400">
        Forge © 2026 • Built for focused, adaptive learning.
      </footer>
    </main>
  );
}
